import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCS4iTYob
bGg+z+uDpnlXzmAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIGA7mst40cIxBk3H
HO4Lu1ol7kwRIp6QF0U5/wb+hzGmAAAAkFShVZwIiEwya03GoRcxYIzwFFZ5Oem7ZM8Cm+
BGtWQvd8wjDtZksXH2sjuVXPsRx4KEATYHrX9A1M3+qdBm/Kw2Tg1fjmR8o0rKPDK2SA8a
aEphQCsI8pwtFM85K2XHJ31QmlXpHYCyF/j8eZgIsR578TnZNs4H1nqFPLvcNvqlS39i6X
nzpFl64SpyY7Hcpw==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
